# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Dadabase"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

      # - dependency-name: "Microsoft.EntityFrameworkCore.InMemory"
      #   versions: [ ">=9.0.0" ]
      # - dependency-name: "Microsoft.EntityFrameworkCore.Tools"
      #   versions: [ ">=9.0.0" ]
      # - dependency-name: "Microsoft.EntityFrameworkCore.Tools"
      #   versions: [ ">=9.0.0" ]
      # - dependency-name: "Swashbuckle.AspNetCore"
      #   versions: [ ">=9.0.0" ]
      # - dependency-name: "Swashbuckle.AspNetCore.Filters"
      #   versions: [ ">=9.0.0" ]

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: weekly
