# ----------------------------------------------------------------------------------------------------
# Template to deploy Azure Resources in a bicep file in one environment
# This template is optimized for a Windows build agent -- see create-infra-linux.yml for a Linux build agent
# ----------------------------------------------------------------------------------------------------
parameters:
- name: environmentName
  default: 'DEV'
- name: templateFolderName
  default: 'infra/Bicep'
- name: templateFileName
  default: 'main.bicep'
- name: parameterFileName
  default: 'main.bicepparam' # 'main.parameters.azdo.json'
- name: deploymentMode
  default: 'Incremental'  # 'Incremental' | 'Complete' | 'Validation'

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: CreateInfra
  displayName: Initialize Create Infra
  environment: ${{ parameters.environmentName }}

- job: CreateInfraJob
  displayName: Create Infrastructure
  variables:
    - name: environmentName
      value: ${{ parameters.environmentName }}
    - name: environmentNameUpper
      value: ${{ upper(parameters.environmentName) }}
    - name: environmentNameLower
      value: ${{ lower(parameters.environmentName) }}
    # If you use Windows Build agents, use the \ delimter, if Ubuntu Linux, use the / delimiter
    - name: templateFile
      value: '$(Pipeline.Workspace)/s/${{ parameters.templateFolderName }}/${{ parameters.templateFileName }}'
    - name: parameterFile
      value: '$(Pipeline.Workspace)/s/${{ parameters.templateFolderName }}/${{ parameters.parameterFileName }}'

    - template: ../../vars/var-common.yml

  # ----------------------------------------------------------------------------------------------------
  steps:
  - bash: |
      appNameLower=$(echo "$(appName)" | tr '[:upper:]' '[:lower:]')
      echo "appName=$(appName)"
      echo "appNameLower=$appNameLower"
      echo "##vso[task.setvariable variable=appNameLower]$appNameLower"

      resourceGroupName=$(echo "$(resourceGroupPrefix)_$(environmentNameLower)" | tr '[:upper:]' '[:lower:]')
      echo "resourceGroupName=$resourceGroupName"
      echo "##vso[task.setvariable variable=resourceGroupName]$resourceGroupName"
      
      runDateTime=$(echo $(date '+%Y%m%d-%H%M%S'))
      echo "##vso[task.setvariable variable=runDateTime]$runDateTime"
      echo "runDateTime=$runDateTime"
                                   
      runDateTimeZ=$(echo $(date '+%Y%m%dT%H%M%SZ'))
      echo "##vso[task.setvariable variable=runDateTimeZ]$runDateTimeZ"
      echo "runDateTimeZ=$runDateTimeZ"
    displayName: 'Create Variables'
    continueOnError: true

  
  - task: Bash@3
    displayName: 'Display Variables'
    continueOnError: true
    inputs:
      targetType: 'inline'
      script: 'env | sort'
    # this script version also works
    # - script: |
    #     for var in $(compgen -e); do
    #       echo $var ${!var};
    #     done
    # and this PowerShell Script works too
    # - task: PowerShell@2
    #   inputs:
    #     targetType: 'inline'
    #     script: Get-ChildItem -Path Env:\ | Format-List
    # - bash: |
    #     echo "Display All Environment Variables:"
    #     printenv | sort
    #   displayName: 'Display Variables'
    #   continueOnError: true
        
  - task: CmdLine@2
    inputs:
      script: |
        echo "Tree and files in pipeline workspace:"
        tree $(Pipeline.Workspace)
    displayName: 'Display Files'
    #condition: eq(variables['AGENT.OS'], 'Windows_NT')
    continueOnError: true

  # Login is needed if you are pulling Bicep files from an Azure Container Registry
  # -script: az login --service-principal -u $(principalId) -p $(clientSecret) --tenant $(tenantId)
  #   displayName: 'az login'

  # Note: this task @v6 changed the parameter NAME from targetFiles to sources
  # - task: qetza.replacetokens.replacetokens-task.replacetokens@6
  #   displayName: 'Create Parameter File'
  #   inputs:
  #     sources: $(parameterFile)
  #     tokenPrefix: '#{'
  #     tokenSuffix: '}#'
  - task: qetza.replacetokens.replacetokens-task.replacetokens@5
    displayName: 'Update Parameter File'
    inputs:
      targetFiles: $(parameterFile)
      tokenPrefix: '#{'
      tokenSuffix: '}#'

  - task: CmdLine@2
    displayName: Display Parameter File Contents
    continueOnError: true
    inputs:
      script: |
        echo "Bicep File Name: $(templateFile)"
        echo "##[group]Contents of Parameter File  $(parameterFile)"
        cat  $(parameterFile)
        echo "##[endgroup]"

  - task: AzureCLI@2
    displayName: 'Create Resource Group'
    inputs:
      azureSubscription: $(serviceConnectionName)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az group create --name $(resourceGroupName) --location $(location) --tags LastDeployed=$(runDateTime) Application=$(appName) Environment=$(environmentNameUpper)

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Publish Bicep Resources'
    inputs:
      csmFile: $(templateFile)
      csmParametersFile: $(parameterFile)
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: $(serviceConnectionName)
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroupName)'
      location: '$(location)'
      templateLocation: 'Linked artifact'
      deploymentMode: '${{ parameters.deploymentMode }}'  # 'Incremental' | 'Complete' | 'Validation'

  - task: CmdLine@2
    inputs:
      script: |
        echo "WIPED!" > $(parameterFile)
    displayName: 'Wipe Parameter File'
    condition: always()
    continueOnError: true
