# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Application Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: runGHASScan
  default: 'false'
- name: runMSDevSecOpsScan
  default: 'false'
- name: runUnitTests
  default: 'false'
- name: runUITests
  default: 'false'

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEMO'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: ${{ parameters.runGHASScan }}

# ----------------------------------------------------------------------------------------------------
- stage: BuildWebApi
  displayName: Build WebApi
  jobs:
  - template: templates/build-webapp-template.yml
    parameters:
      environmentName: 'DEV'
      runUnitTests: ${{ parameters.runUnitTests }}

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: DeployApp${{ environmentName }}
    displayName: Deploy ${{ environmentName }} Application
    jobs:
    - template: templates/deploy-webapp-template.yml
      parameters:
        environmentName: ${{ environmentName }}

  - ${{ if eq(lower(parameters.runUITests), 'true') }}:
    - stage: UITest${{ environmentName }}WebApp
      displayName: UI Test ${{ environmentName }}
      dependsOn: DeployApp${{ environmentName }}
      condition: succeeded('DeployApp${{ environmentName }}')
      variables:
        - template: ../vars/var-common.yml
      jobs:
      - template: templates/playwright-template.yml
        parameters:
          environment: ${{ environmentName }}
          testType: ${{ variables.playwrightUITestType }}
          testPath: ${{ variables.playwrightUITestPath }}
          debug: true
