# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to run the smoke tests only
# ------------------------------------------------------------------------------------------------------------------------
# FYI: You need to set up some secrets before running this workflows - see CreateGitHubSecrets.md for details.
# ------------------------------------------------------------------------------------------------------------------------
name: 5.smoke.test
run-name: '5 - Smoke Test by @${{ github.actor }} using ENV ${{ inputs.deployEnvironment }} '

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        required: true
        default: 'dev' 
        type: environment
      logLevel:
        description: Log level
        required: false
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 
    
# ------------------------------------------------------------------------------------------------------------------------
jobs:
  run-smoke-test:
    name: Smoke Test ${{ inputs.deployEnvironment }}
    uses: ./.github/workflows/template-smoke-test.yml
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      testPath: 'playwright/ui-tests'
      testType: 'ui'
