# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to Scan Bicep on a schedule
# ------------------------------------------------------------------------------------------------------------------------
name: 7.scan.devsecops.scheduled
run-name: '7 - Scheduled Scan'

on:
  workflow_dispatch:
    inputs:
      runMSDevSecOpsScan:
        description: Run MS DevSecOps Scan
        default: true
        type: boolean
      runGHASScan:
        description: Run GitHub Advanced Security Scan
        default: true
        type: boolean
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    # run this every weekday at 3am even if no pushes or PRs
    - cron: '0 3 * * 1-5'
    # # run this once a month on the 1st day of the month even if no pushes or PRs
    # - cron: '0 0 1 * *'
# ------------------------------------------------------------------------------------------------------------------------
permissions:
  id-token: write
  contents: write
  actions: read
  pages: write
  security-events: write
  checks: write
  issues: read
  pull-requests: read
  packages: read

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  ms-devsecops-scan:
    name: MS DevSecOps Scan
    if: inputs.runMSDevSecOpsScan
    uses: ./.github/workflows/template-scanning-code.yml
    secrets: inherit
    with:
      runMSDevSecOpsScan: ${{ inputs.runMSDevSecOpsScan }}
      runGHASScan: false

  codeql-scan:
    name: CodeQL Scan
    if: inputs.runGHASScan
    uses: ./.github/workflows/template-scanning-code.yml
    secrets: inherit
    with:
      runGHASScan: ${{ inputs.runGHASScan }}
      runMSDevSecOpsScan: false