# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to Scan Bicep on a schedule
# ------------------------------------------------------------------------------------------------------------------------
name: 7.scan.devsecops.scheduled
run-name: '7 - Scheduled Scan'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # run this once a month on the 1st day of the month even if no pushes or PRs
  schedule:
    - cron: '0 0 1 * *'
  
# ------------------------------------------------------------------------------------------------------------------------
permissions:
  id-token: write
  contents: write
  actions: read
  pages: write
  security-events: write
  checks: write
  issues: read
  pull-requests: read

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  scan-code:
    name: Scan Source Code
    uses: ./.github/workflows/template-scan-code.yml
    secrets: inherit
    with:
      runSecurityScan: true
