# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources and WebApp
# ------------------------------------------------------------------------------------------------------------------------
# FYI: You need to set up some secrets before running this workflows - see CreateGitHubSecrets.md for details.
# ------------------------------------------------------------------------------------------------------------------------
name: bicep.build.deploy.webapp
on: 
  workflow_dispatch:
    inputs:
      runSecurityScan:
        description: 'Run Security Scan'
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      runCreateInfra:
        description: 'Deploy Bicep'
        required: false
        default: 'true'
        type: choice
        options:
          - true
          - false
      runBuildDeploy:
        description: 'Build and Deploy App'
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      runSmokeTest:
        description: 'Run Smoke Tests'
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

jobs:
# ------------------------------------------------------------------------------------------------------------------------
  scan-code:
    name: Scan Source Code
    uses: ./.github/workflows/template.scan.code.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
      checks: write
    with:
      runSecurityScan: ${{ inputs.runSecurityScan == 'true' }}

  # ------------------------------------------------------------------------------------------------------------------------
  create-infra:
    name: Create Infra
    uses: ./.github/workflows/template.create.infra.yml
    if: inputs.runCreateInfra == 'true' || inputs.runBuildDeploy == 'true'
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      issues: read
      checks: write
    with:
      envCode: 'dev'
      templatePath: './infra/Bicep/'
      templateFile: 'main.bicep'
      parameterFile: 'main.parameters.gha.bicepparam'
      parameterFileReplaceTokens: 'true'
      runCreateInfra: ${{ inputs.runCreateInfra == 'true' }}

# ------------------------------------------------------------------------------------------------------------------------
  build-app:
    name: Build WebApp
    uses: ./.github/workflows/template.webapp.build.yml
    if: inputs.runBuildDeploy == 'true' || inputs.runSmokeTest == 'true'
    needs: create-infra
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pull-requests: read
      issues: read
      checks: write
    with:
      envCode: 'dev'
      rootDirectory: '${{ vars.APP_PROJECT_FOLDER_NAME }}'
      projectName: '${{ vars.APP_PROJECT_NAME }}'
      testDirectory: '${{ vars.APP_TEST_FOLDER_NAME }}'
      testProjectName: '${{ vars.APP_TEST_PROJECT_NAME }}'
      testApplication: true
      listFilesAfterBuild: true

# ------------------------------------------------------------------------------------------------------------------------
  deploy-app:
    name: Deploy WebApp
    uses: ./.github/workflows/template.webapp.deploy.yml
    if: inputs.runBuildDeploy == 'true' || inputs.runSmokeTest == 'true'
    needs: build-app
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
    with:
      envCode: 'dev'

      
# ------------------------------------------------------------------------------------------------------------------------
  run-smoke-test:
    name: Test WebApp
    uses: ./.github/workflows/template.smoke.test.yml
    if: inputs.runSmokeTest == 'true'
    needs: deploy-app
    secrets: inherit
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: read
    with:
      envCode: 'dev'
