# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to run the smoke tests only
# ------------------------------------------------------------------------------------------------------------------------
# FYI: You need to set up some secrets before running this workflows - see CreateGitHubSecrets.md for details.
# ------------------------------------------------------------------------------------------------------------------------
name: run.smoke.test.only
on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: 'Environment'
        required: true
        default: 'dev' 
        type: choice
        options:
          - dev
          - qa
          - prod
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 
    
# ------------------------------------------------------------------------------------------------------------------------
jobs:
  run-smoke-test:
    name: Test ${{ inputs.deployEnvironment }} Environment
    uses: ./.github/workflows/template.smoke.test.yml
    secrets: inherit
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: read
    with:
      envCode: 'dev'
