# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: template.create.infra
run-name: Deploy Infra Bicep
on:
  workflow_call:
    inputs:
      envCode:
        required: true
        type: string

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  deploy:
    name: Create Infra
    runs-on: ubuntu-latest  #windows-latest
    environment:
      name: ${{ inputs.envCode }}
    
    env:
      generatedAppEnvName: ${{ vars.APP_NAME }}-${{ inputs.envCode }}
      generatedResourceGroupName: ${{ vars.RESOURCEGROUP_PREFIX }}_${{ inputs.envCode }}

    steps:
    - name: Display Variables
      run: |-
        echo 'environmentCode=${{ inputs.envCode }}'
        echo 'env.generatedAppEnvName=${{ env.generatedAppEnvName }}'
        echo 'env.generatedResourceGroupName=${{ env.generatedResourceGroupName }}'
        echo '${{ toJSON(vars) }}'
      continue-on-error: true

    - name: Checkout Code
      uses: actions/checkout@main

    - name: Replace Tokens
      uses: qetza/replacetokens-action@v1
      with:
        sources: '**/*.parameters.gha.json; !local/ => out/*.parameters.gha.json'
        variables: '[${{ toJSON(vars) }},${{ toJSON(secrets) }}]' # use variables & secrets
      
    - name: Display Files
      run: 
        tree ${{ env.GITHUB_ACTION_PATH }}
      continue-on-error: true
  
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Create Resource Group
      run: 
        az group create --name ${{ env.generatedResourceGroupName }} --location ${{ vars.RESOURCEGROUP_LOCATION }} --tags Environment=${{ inputs.envCode }} Application=${{ vars.APP_NAME }}

    - name: Deploy Azure Resources
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.generatedResourceGroupName }}
        template: infra/Bicep/main.bicep
        parameters: infra/Bicep/out/main.parameters.gha.json environmentCode=${{ inputs.envCode }}
