# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
# FYI: You need to set up some secrets before running this workflows - see CreateGitHubSecrets.md for details.
# ------------------------------------------------------------------------------------------------------------------------
name: z_template_deploy_infra
run-name: Deploy Infra Bicep
on:
  workflow_call:
    inputs:
      envCode:
        required: true
        type: string
      templatePath: 
        required: false
        type: string
        default: 'infra/Bicep/'
      templateFile: 
        required: false
        type: string
        default: 'main.bicep'
      parameterFile: 
        required: false
        type: string
        default: ''
      parameterFileReplaceTokens: 
        required: false
        type: string
        default: 'false'
      deploymentMode: 
        required: false
        type: string
        default: 'Incremental'
      runCreateInfra:
        required: false
        default: true
        type: boolean

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  deploy:
    name: Deploy Bicep
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.envCode }}
    permissions:
      id-token: write    
      contents: read     
      actions: read      
    
    # ------------------------------------------------------------------------------------------------------------------------
    # Variables
    # ------------------------------------------------------------------------------------------------------------------------
    env:
      generatedAppEnvName: ${{ vars.APP_NAME }}-${{ inputs.envCode }}
      generatedResourceGroupName: ${{ vars.RESOURCEGROUP_PREFIX }}_${{ inputs.envCode }}

    # ------------------------------------------------------------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------------------------------------------------------------
    steps:
    - name: Create Variables
      run: |
        if [[ $parameterFile == '' ]]; then
            echo "parameterFilePath=" >> "$GITHUB_ENV"
        else
            echo "parameterFilePath=${{ inputs.templatePath }}${{ inputs.parameterFile }}" >> "$GITHUB_ENV"
        fi

    - name: Display Variables
      run: |-
        echo 'env.generatedAppEnvName=${{ env.generatedAppEnvName }}'
        echo 'env.generatedResourceGroupName=${{ env.generatedResourceGroupName }}'
        echo "location=${{ vars.RESOURCEGROUP_LOCATION }}"
        echo "envCode=${{ inputs.envCode }}"
        echo "templatePath=${{ inputs.templatePath }}"
        echo "templateFile=${{ inputs.templateFile }}"
        echo "templateFilePath=${{ inputs.templatePath }}${{ inputs.templateFile }}"
        echo "parameterFile=${{ inputs.parameterFile }}"
        echo "parameterFilePath=${{ env.parameterFilePath }}"
        echo "parameterFileReplaceTokens=${{ inputs.parameterFileReplaceTokens }}"
        echo "---------------------------------"
        echo "All Variables:"
        echo '${{ toJSON(vars) }}'
        echo "---------------------------------"
        echo "Files in ${{ github.action_path }}"
        ls ${{ github.action_path }}
      continue-on-error: true

    - name: Checkout Code
      if: ${{ inputs.runCreateInfra }}
      uses: actions/checkout@main

    - name: Replace Tokens
      if: ${{ inputs.runCreateInfra && inputs.parameterFileReplaceTokens == 'true' }}
      uses: qetza/replacetokens-action@v1
      with:
        sources: '${{ inputs.templatePath }}${{ inputs.parameterFile }}; !local/ => ${{ inputs.parameterFile }}'
        variables: '[${{ toJSON(vars) }},${{ toJSON(secrets) }}]' # use variables & secrets
      
    # Login with OpenID Connect
    # - name: Log into Azure
    #   uses: azure/login@v2
    #   with:
    #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    # Login with Client Secret
    - name: Log into Azure
      if: ${{ inputs.runCreateInfra }}
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Create Resource Group
      run: 
        az group create --name ${{ env.generatedResourceGroupName }} --location ${{ vars.RESOURCEGROUP_LOCATION }} --tags Environment=${{ inputs.envCode }}

    - name: Deploy Azure Resources
      uses: azure/arm-deploy@v2
      if: ${{ inputs.runCreateInfra }}
      id: deploy-bicep
      with:
        scope: resourcegroup
        region: ${{ vars.RESOURCEGROUP_LOCATION }}
        resourceGroupName: ${{ env.generatedResourceGroupName }}
        template: ${{ inputs.templatePath }}${{ inputs.templateFile }}
        parameters: ${{ env.parameterFilePath }}
        deploymentMode: ${{ inputs.deploymentMode }} # Must be: Incremental | Complete | Validation

    - name: Display Output
      if: ${{ inputs.runCreateInfra }}
      run: |-
        echo ${{ steps.deploy-bicep.outputs.resourceToken }}
        echo ${{ steps.deploy-bicep.outputs.hostName }}
      continue-on-error: true

    - name: Write summary
      if: ${{ inputs.runCreateInfra }}
      env:
        SUMMARY: |
          # Deployment summary
          - Target Resource Group: ${{ env.generatedResourceGroupName }}
          - Link to App URL: [https://${{ steps.deploy-bicep.outputs.hostName }}](https://${{ steps.deploy-bicep.outputs.hostName }})
          # GitHub Action Variables
          - Set the GitHub repository variable RESOURCE_TOKEN to: ${{ steps.deploy-bicep.outputs.resourceToken }}
      run: echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
      continue-on-error: true
